class Connect_err(Exception):
    pass